### ISSUE TITLE
Incomplete code for Run_CONISCmat.r

### ISSUE THREAD

**Issue by zhou-ran** [linwang6/Glioblastoma_paper#1]
Hi, thanks for publishing your analysis process.
But some of process in Run_CONICSmat.r is missing, could you provide the missing part? 
I can't repeat the result for identifying tumor cells in your article.
Thanks

**Comment by linwang6** [comment]
Hi, the code is complete for running CONICS, I not totally understand what you mean here for the missing part. If you want to see more detail for CONICS, please refer the detailed tutorial https://github.com/diazlab/CONICS. Hope it helps.

**Comment by zhou-ran** [comment]
Hi, I don't know how you get the pre-processing matrix (glioma_CNV) for running CONICS, and following the tutorial, I can't get same clonal CNV results for each patient which showed in table S1. I'm not sure if there is any difference  in somewhere and caused the difference results.

**Comment by zhou-ran** [comment]
I also can't get any information about why you choose cluster3 and regard it as normal cell from your paper or code.

**Comment by linwang6** [comment]
Hi, I got what you mean now, here is just one example for running CONICS, cluster3 (normal) is for one example sample. For pre-processing matrix, please refer tutorial https://github.com/diazlab/CONICS, there are detailed steps...

**Comment by zhou-ran** [comment]
谢谢王林老师的回复。我也不知道为什么一个reviewer非得要我处理这个数据来看一下，╭(╯^╰)╮

**Comment by zhou-ran** [comment]
Hi, could you generously send me all neoplastic cell list?

**Comment by linwang6** [comment]
Hi, the files are scattered in different area, not handy, I would like to suggest you to run CONICS...

**Comment by zhou-ran** [comment]
OK, Thank you for your prompt reply, and I think i have get the results.
